name = "partygame-example-backend"
main = "src/index.ts"
compatibility_date = "2026-05-18"

[[durable_objects.bindings]]
name = "GAME_ROOM"
class_name = "GameRoom"

[[durable_objects.bindings]]
name = "MATCHMAKER_ROOM"
class_name = "MatchmakerRoom"

[[migrations]]
tag = "v2"
new_sqlite_classes = ["MatchmakerRoom"]

[[r2_buckets]]
binding = "PLATFORM_BUCKET"
bucket_name = "partygame-platform"
