// Placeholder — regenerated by "npm run build-admin"
export const ADMIN_INDEX_HTML = "<!DOCTYPE html><html><head><meta charset=utf-8><title>PartyGame</title></head><body><div id=root></div><p>Run: npm run build-admin</p></body></html>";
