// Auto-generated by PartyGame for Unreal Engine
#pragma once

#include "CoreMinimal.h"
#include "PartyGameTypes.generated.h"

USTRUCT(BlueprintType)
struct FPartyGameVector3
{
    GENERATED_BODY()
    UPROPERTY(EditAnywhere, BlueprintReadWrite) float X = 0.0f;
    UPROPERTY(EditAnywhere, BlueprintReadWrite) float Y = 0.0f;
    UPROPERTY(EditAnywhere, BlueprintReadWrite) float Z = 0.0f;
};

USTRUCT(BlueprintType)
struct FPartyGamePlayerState
{
    GENERATED_BODY()
    UPROPERTY(EditAnywhere, BlueprintReadWrite) FString Id;
    UPROPERTY(EditAnywhere, BlueprintReadWrite) FPartyGameVector3 Position;
    UPROPERTY(EditAnywhere, BlueprintReadWrite) FPartyGameVector3 Rotation;
    UPROPERTY(EditAnywhere, BlueprintReadWrite) float Health = 0.0f;
};

USTRUCT(BlueprintType)
struct FPartyGamePurchaseRequest
{
    GENERATED_BODY()
    UPROPERTY(EditAnywhere, BlueprintReadWrite) FString ItemId;
    UPROPERTY(EditAnywhere, BlueprintReadWrite) float Cost = 0.0f;
    UPROPERTY(EditAnywhere, BlueprintReadWrite) FString IdempotencyKey;
};
