# Auto-generated by PartyGame
class_name PartyGameTypes

class TransformComponent:
	var x: float
	var y: float
	var rotation: float
	var scale_x: float
	var scale_y: float

class HealthComponent:
	var hp: float
	var max_hp: float
	var is_dead: bool

class VelocityComponent:
	var vx: float
	var vy: float

class InputComponent:
	var move_x: float
	var move_y: float
	var is_jumping: bool
	var is_sprinting: bool
