# Auto-generated by PartyGame
class_name PartyGameTypes

class Vector3State:
	var x: float
	var y: float
	var z: float

class PlayerState:
	var id: String
	var position: Vector3State
	var rotation: Vector3State
	var health: float

class PurchaseRequest:
	var item_id: String
	var cost: float
	var idempotency_key: String
