// Auto-generated by PartyGame
using System;

namespace PartyGame.Generated
{
    [Serializable]
    public class Vector3 { public float x; public float y; public float z; }

    [Serializable]
    public class PlayerState { public string id; public Vector3 position; public Vector3 rotation; public float health; }

    [Serializable]
    public class PurchaseRequest { public string itemId; public float cost; public string idempotencyKey; }
}
