using System;
using System.Net.Http;
using System.Net.WebSockets;
using System.Text;
using System.Threading;
using System.Threading.Tasks;

// Auto-Generated by openapi-generator (mocked due to missing Java)
namespace PartyGameSDK
{
    [Serializable]
    public class LoginRequest
    {
        public string playerId;
        public string playerName;
    }

    [Serializable]
    public class AuthResponse
    {
        public string token;
        public string playerId;
        public string playerName;
        public string expiresAt;
    }

    [Serializable]
    public class JoinMatchRequest
    {
        public string playerId;
        public string gameType;
    }

    public class NetworkManager
    {
        private readonly HttpClient _http;
        private ClientWebSocket _ws;
        private string _baseUrl;
        private string _token;
        private string _playerId;

        public event Action<string> OnMessageReceived;

        public NetworkManager(string baseUrl)
        {
            _baseUrl = baseUrl.TrimEnd('/');
            _http = new HttpClient();
        }

        public async Task<AuthResponse> LoginAsync(string playerId, string playerName)
        {
            var req = new LoginRequest { playerId = playerId, playerName = playerName };
            var json = UnityEngine.JsonUtility.ToJson(req); // Assuming Unity
            var content = new StringContent(json, Encoding.UTF8, "application/json");

            var res = await _http.PostAsync($"{_baseUrl}/auth/login", content);
            res.EnsureSuccessStatusCode();

            var resJson = await res.Content.ReadAsStringAsync();
            var auth = UnityEngine.JsonUtility.FromJson<AuthResponse>(resJson);
            
            _token = auth.token;
            _playerId = auth.playerId;
            return auth;
        }

        public async Task JoinMatchmakerAsync(string gameType = "moba")
        {
            var req = new JoinMatchRequest { playerId = _playerId, gameType = gameType };
            var json = UnityEngine.JsonUtility.ToJson(req);
            var content = new StringContent(json, Encoding.UTF8, "application/json");

            var res = await _http.PostAsync($"{_baseUrl}/matchmaking/join", content);
            res.EnsureSuccessStatusCode();
        }

        public async Task ConnectWebSocketAsync(string roomId, string gameType = "moba")
        {
            _ws = new ClientWebSocket();
            var wsUrl = _baseUrl.Replace("http", "ws") + 
                $"/ws?roomId={roomId}&playerId={_playerId}&token={_token}&gameType={gameType}";

            await _ws.ConnectAsync(new Uri(wsUrl), CancellationToken.None);
            _ = ReceiveLoopAsync();
        }

        private async Task ReceiveLoopAsync()
        {
            var buffer = new byte[8192];
            while (_ws.State == WebSocketState.Open)
            {
                var result = await _ws.ReceiveAsync(new ArraySegment<byte>(buffer), CancellationToken.None);
                if (result.MessageType == WebSocketMessageType.Close)
                {
                    await _ws.CloseAsync(WebSocketCloseStatus.NormalClosure, "Closed", CancellationToken.None);
                    break;
                }
                else if (result.MessageType == WebSocketMessageType.Text)
                {
                    var msg = Encoding.UTF8.GetString(buffer, 0, result.Count);
                    OnMessageReceived?.Invoke(msg);
                }
                // Binary payloads can be routed to OnBinaryMessageReceived
            }
        }

        public async Task SendBinaryAsync(byte[] data)
        {
            if (_ws?.State == WebSocketState.Open)
            {
                await _ws.SendAsync(new ArraySegment<byte>(data), WebSocketMessageType.Binary, true, CancellationToken.None);
            }
        }
    }
}
