// Auto-generated by PartyGame for Unreal Engine
#pragma once

#include "CoreMinimal.h"
#include "PartyGameTypes.generated.h"

USTRUCT(BlueprintType)
struct FPartyGameTransformComponent
{
    GENERATED_BODY()
    UPROPERTY(EditAnywhere, BlueprintReadWrite) float X;
    UPROPERTY(EditAnywhere, BlueprintReadWrite) float Y;
    UPROPERTY(EditAnywhere, BlueprintReadWrite) float Rotation;
    UPROPERTY(EditAnywhere, BlueprintReadWrite) float ScaleX;
    UPROPERTY(EditAnywhere, BlueprintReadWrite) float ScaleY;
};

// Auto-generated by PartyGame for Unreal Engine
#pragma once

#include "CoreMinimal.h"
#include "PartyGameTypes.generated.h"

USTRUCT(BlueprintType)
struct FPartyGameHealthComponent
{
    GENERATED_BODY()
    UPROPERTY(EditAnywhere, BlueprintReadWrite) float Hp;
    UPROPERTY(EditAnywhere, BlueprintReadWrite) float MaxHp;
    UPROPERTY(EditAnywhere, BlueprintReadWrite) bool IsDead;
};

// Auto-generated by PartyGame for Unreal Engine
#pragma once

#include "CoreMinimal.h"
#include "PartyGameTypes.generated.h"

USTRUCT(BlueprintType)
struct FPartyGameVelocityComponent
{
    GENERATED_BODY()
    UPROPERTY(EditAnywhere, BlueprintReadWrite) float Vx;
    UPROPERTY(EditAnywhere, BlueprintReadWrite) float Vy;
};

// Auto-generated by PartyGame for Unreal Engine
#pragma once

#include "CoreMinimal.h"
#include "PartyGameTypes.generated.h"

USTRUCT(BlueprintType)
struct FPartyGameInputComponent
{
    GENERATED_BODY()
    UPROPERTY(EditAnywhere, BlueprintReadWrite) float MoveX;
    UPROPERTY(EditAnywhere, BlueprintReadWrite) float MoveY;
    UPROPERTY(EditAnywhere, BlueprintReadWrite) bool IsJumping;
    UPROPERTY(EditAnywhere, BlueprintReadWrite) bool IsSprinting;
};
