// Auto-generated by PartyGame for Unreal Engine
#pragma once

#include "CoreMinimal.h"
#include "PartyGameTypes.generated.h"

USTRUCT(BlueprintType)
struct FPartyGameVector3
{
    GENERATED_BODY()
    UPROPERTY(EditAnywhere, BlueprintReadWrite) float X;
    UPROPERTY(EditAnywhere, BlueprintReadWrite) float Y;
    UPROPERTY(EditAnywhere, BlueprintReadWrite) float Z;
};

// Auto-generated by PartyGame for Unreal Engine
#pragma once

#include "CoreMinimal.h"
#include "PartyGameTypes.generated.h"

USTRUCT(BlueprintType)
struct FPartyGamePlayerState
{
    GENERATED_BODY()
    UPROPERTY(EditAnywhere, BlueprintReadWrite) FString Id;
    UPROPERTY(EditAnywhere, BlueprintReadWrite) FPartyGameVector3 Position;
    UPROPERTY(EditAnywhere, BlueprintReadWrite) FPartyGameVector3 Rotation;
    UPROPERTY(EditAnywhere, BlueprintReadWrite) float Health;
};

// Auto-generated by PartyGame for Unreal Engine
#pragma once

#include "CoreMinimal.h"
#include "PartyGameTypes.generated.h"

USTRUCT(BlueprintType)
struct FPartyGamePurchaseRequest
{
    GENERATED_BODY()
    UPROPERTY(EditAnywhere, BlueprintReadWrite) FString ItemId;
    UPROPERTY(EditAnywhere, BlueprintReadWrite) float Cost;
    UPROPERTY(EditAnywhere, BlueprintReadWrite) FString IdempotencyKey;
};
