import {
  TransformComponentSchema,
  HealthComponentSchema,
  VelocityComponentSchema,
  InputComponentSchema,
} from "./schemas";

import { z } from "zod";

type PrimitiveKind = "string" | "number" | "boolean";

type TargetNames = {
  csharp: string;
  godot: string;
  unreal: string;
};

type FieldDescriptor = {
  name: string;
  kind: PrimitiveKind | "object";
  reference?: TargetNames;
};

type SchemaDescriptor = {
  name: string;
  targets: TargetNames;
  fields: FieldDescriptor[];
};

const schemaTargets = new Map<unknown, TargetNames>([
  [
    TransformComponentSchema,
    {
      csharp: "TransformComponent",
      godot: "TransformComponent",
      unreal: "FPartyGameTransformComponent",
    },
  ],
  [
    HealthComponentSchema,
    {
      csharp: "HealthComponent",
      godot: "HealthComponent",
      unreal: "FPartyGameHealthComponent",
    },
  ],
  [
    VelocityComponentSchema,
    {
      csharp: "VelocityComponent",
      godot: "VelocityComponent",
      unreal: "FPartyGameVelocityComponent",
    },
  ],
  [
    InputComponentSchema,
    {
      csharp: "InputComponent",
      godot: "InputComponent",
      unreal: "FPartyGameInputComponent",
    },
  ],
] as const);

const rootSchemas = [
  { name: "TransformComponent", schema: TransformComponentSchema },
  { name: "HealthComponent", schema: HealthComponentSchema },
  { name: "VelocityComponent", schema: VelocityComponentSchema },
  { name: "InputComponent", schema: InputComponentSchema },
] as const;

function unwrapSchema(schema: unknown): unknown {
  let current = schema as { _def?: { innerType?: unknown; schema?: unknown } };

  while (current && typeof current === "object") {
    const next = current._def?.innerType ?? current._def?.schema;
    if (!next) {
      break;
    }
    current = next as { _def?: { innerType?: unknown; schema?: unknown } };
  }

  return current;
}

function toSnakeCase(value: string): string {
  return value
    .replace(/([a-z0-9])([A-Z])/g, "$1_$2")
    .replace(/[-\s]+/g, "_")
    .toLowerCase();
}

function describeField(fieldSchema: unknown): FieldDescriptor {
  const unwrapped = unwrapSchema(fieldSchema);

  if (!unwrapped || typeof unwrapped !== "object") {
    throw new Error("Unsupported schema field.");
  }

  if (unwrapped instanceof z.ZodString) {
    return { name: "", kind: "string" };
  }

  if (unwrapped instanceof z.ZodNumber) {
    return { name: "", kind: "number" };
  }

  if (unwrapped instanceof z.ZodBoolean) {
    return { name: "", kind: "boolean" };
  }

  const target = schemaTargets.get(unwrapped as never);
  if (target) {
    return { name: "", kind: "object", reference: target };
  }

  const descriptor = unwrapped as { _def?: { typeName?: string } };
  const typeName = descriptor._def?.typeName;
  throw new Error(`Unsupported schema field type: ${String(typeName)}`);
}

function describeSchema(
  name: string,
  schema: z.ZodTypeAny,
): SchemaDescriptor {
  const def = schema as unknown as {
    _def?: { shape?: Record<string, unknown> | (() => Record<string, unknown>) };
  };

  const shapeValue =
    typeof def._def?.shape === "function" ? def._def.shape() : def._def?.shape;

  if (!shapeValue || typeof shapeValue !== "object") {
    throw new Error(`Schema ${name} is not an object schema.`);
  }

  const shape = shapeValue as Record<string, unknown>;
  const fields = Object.entries(shape).map(([fieldName, fieldSchema]) => {
    const field = describeField(fieldSchema);
    return {
      ...field,
      name: fieldName,
    };
  });

  const targets = schemaTargets.get(schema);
  if (!targets) {
    throw new Error(`Missing target names for schema: ${name}`);
  }

  return {
    name,
    targets,
    fields,
  };
}

function renderCSharp(schema: SchemaDescriptor): string {
  const lines = schema.fields.map((field) => {
    const fieldType =
      field.kind === "object"
        ? field.reference?.csharp
        : field.kind === "string"
          ? "string"
          : field.kind === "number"
            ? "float"
            : "bool";
    const fieldName = field.name;
    return `    public ${fieldType} ${fieldName};`;
  });

  return `// Auto-generated by PartyGame
using System;

namespace PartyGame.Generated
{
    [Serializable]
    public class ${schema.targets.csharp}
    {
${lines.join("\n")}
    }
}
`;
}

function renderGodot(schema: SchemaDescriptor): string {
  const lines = schema.fields.map((field) => {
    const fieldType =
      field.kind === "object"
        ? field.reference?.godot
        : field.kind === "string"
          ? "String"
          : field.kind === "number"
            ? "float"
            : "bool";
    return `\tvar ${toSnakeCase(field.name)}: ${fieldType}`;
  });

  return `class ${schema.targets.godot}:
${lines.join("\n")}
`;
}

function renderUnreal(schema: SchemaDescriptor): string {
  const lines = schema.fields.map((field) => {
    const fieldType =
      field.kind === "object"
        ? field.reference?.unreal
        : field.kind === "string"
          ? "FString"
          : field.kind === "number"
            ? "float"
            : "bool";
    const fieldName = field.kind === "object" ? field.name : field.name;
    const propertyName = fieldName.charAt(0).toUpperCase() + fieldName.slice(1);
    return `    UPROPERTY(EditAnywhere, BlueprintReadWrite) ${fieldType} ${propertyName};`;
  });

  return `// Auto-generated by PartyGame for Unreal Engine
#pragma once

#include "CoreMinimal.h"
#include "PartyGameTypes.generated.h"

USTRUCT(BlueprintType)
struct ${schema.targets.unreal}
{
    GENERATED_BODY()
${lines.join("\n")}
};
`;
}

export type GeneratedArtifacts = Record<string, string>;

export function buildGeneratedArtifacts(): GeneratedArtifacts {
  const descriptors = rootSchemas.map(({ name, schema }) =>
    describeSchema(name, schema),
  );

  const artifacts: GeneratedArtifacts = {
    "unity/package.json": JSON.stringify(
      {
        name: "com.partygame.core",
        version: "0.0.1",
        displayName: "PartyGame SDK",
        description:
          "Auto-generated PartyGame multiplayer types and client SDK.",
        unity: "2021.3",
      },
      null,
      2,
    ),
    "unity/PartyGame.asmdef": JSON.stringify(
      {
        name: "PartyGame",
        references: [],
        includePlatforms: [],
        excludePlatforms: [],
        allowUnsafeCode: false,
        overrideReferences: false,
        precompiledReferences: [],
        autoReferenced: true,
        defineConstraints: [],
        versionDefines: [],
        noEngineReferences: false,
      },
      null,
      2,
    ),
    "godot/addons/partygame/plugin.cfg": `[plugin]\n\nname="PartyGame SDK"\ndescription="Auto-generated PartyGame multiplayer types and client SDK."\nauthor="PartyGame"\nversion="0.0.1"\nscript="edge_pulse_plugin.gd"\n`,
    "godot/addons/partygame/edge_pulse_plugin.gd": `@tool\nextends EditorPlugin\n\nfunc _enter_tree():\n\tpass\n\nfunc _exit_tree():\n\tpass\n`,
    "unreal/PartyGame/PartyGame.uplugin": JSON.stringify(
      {
        FileVersion: 3,
        Version: 1,
        VersionName: "0.0.1",
        FriendlyName: "PartyGame SDK",
        Description:
          "Auto-generated PartyGame multiplayer types and client SDK.",
        Category: "Networking",
        CreatedBy: "PartyGame",
        CanContainContent: true,
        IsBetaVersion: false,
        IsExperimentalVersion: false,
        Installed: false,
        Modules: [
          { Name: "PartyGame", Type: "Runtime", LoadingPhase: "Default" },
        ],
      },
      null,
      2,
    ),
    "unreal/PartyGame/Source/PartyGame/PartyGame.Build.cs": `using UnrealBuildTool;\n\npublic class PartyGame : ModuleRules\n{\n\tpublic PartyGame(ReadOnlyTargetRules Target) : base(Target)\n\t{\n\t\tPCHUsage = ModuleRules.PCHUsageMode.UseExplicitOrSharedPCHs;\n\t\tPublicDependencyModuleNames.AddRange(new string[] { "Core", "CoreUObject", "Engine" });\n\t}\n}\n`,
    "unreal/PartyGame/Source/PartyGame/Private/PartyGameModule.cpp": `#include "Modules/ModuleManager.h"\nIMPLEMENT_MODULE(FDefaultModuleImpl, PartyGame);\n`,
  };

  artifacts["unity/Runtime/PartyGameTypes.cs"] = descriptors
    .map(renderCSharp)
    .join("\n");
  artifacts["godot/addons/partygame/edge_pulse_types.gd"] =
    `# Auto-generated by PartyGame
class_name PartyGameTypes

${descriptors.map(renderGodot).join("\n")}`;
  artifacts["unreal/PartyGame/Source/PartyGame/Public/PartyGameTypes.h"] =
    descriptors.map(renderUnreal).join("\n");

  return artifacts;
}

export function getGeneratedArtifactPaths(): string[] {
  return Object.keys(buildGeneratedArtifacts());
}
