import {
  Vector3Schema,
  PlayerStateSchema,
  PurchaseRequestSchema,
} from "./schemas";

type PrimitiveKind = "string" | "number" | "boolean";

type TargetNames = {
  csharp: string;
  godot: string;
  unreal: string;
};

type FieldDescriptor = {
  name: string;
  kind: PrimitiveKind | "object";
  reference?: TargetNames;
};

type SchemaDescriptor = {
  name: string;
  targets: TargetNames;
  fields: FieldDescriptor[];
};

const schemaTargets = new Map<unknown, TargetNames>([
  [
    Vector3Schema,
    { csharp: "Vector3", godot: "Vector3State", unreal: "FPartyGameVector3" },
  ],
  [
    PlayerStateSchema,
    {
      csharp: "PlayerState",
      godot: "PlayerState",
      unreal: "FPartyGamePlayerState",
    },
  ],
  [
    PurchaseRequestSchema,
    {
      csharp: "PurchaseRequest",
      godot: "PurchaseRequest",
      unreal: "FPartyGamePurchaseRequest",
    },
  ],
] as const);

const rootSchemas = [
  { name: "Vector3", schema: Vector3Schema },
  { name: "PlayerState", schema: PlayerStateSchema },
  { name: "PurchaseRequest", schema: PurchaseRequestSchema },
] as const;

function toSnakeCase(value: string): string {
  return value
    .replace(/([a-z0-9])([A-Z])/g, "$1_$2")
    .replace(/[-\s]+/g, "_")
    .toLowerCase();
}

function describeField(fieldSchema: unknown): FieldDescriptor {
  if (!fieldSchema || typeof fieldSchema !== "object") {
    throw new Error("Unsupported schema field.");
  }

  const descriptor = fieldSchema as { _def?: { typeName?: string } };
  const typeName = descriptor._def?.typeName;

  if (typeName === "ZodString") {
    return { name: "", kind: "string" };
  }

  if (typeName === "ZodNumber") {
    return { name: "", kind: "number" };
  }

  if (typeName === "ZodBoolean") {
    return { name: "", kind: "boolean" };
  }

  const target = schemaTargets.get(fieldSchema as never);
  if (target) {
    return { name: "", kind: "object", reference: target };
  }

  throw new Error(`Unsupported schema field type: ${String(typeName)}`);
}

function describeSchema(
  name: string,
  schema:
    | typeof Vector3Schema
    | typeof PlayerStateSchema
    | typeof PurchaseRequestSchema,
): SchemaDescriptor {
  const shape = schema._def.shape();
  const fields = Object.entries(shape).map(([fieldName, fieldSchema]) => {
    const field = describeField(fieldSchema);
    return {
      ...field,
      name: fieldName,
    };
  });

  const targets = schemaTargets.get(schema);
  if (!targets) {
    throw new Error(`Missing target names for schema: ${name}`);
  }

  return {
    name,
    targets,
    fields,
  };
}

function renderCSharp(schema: SchemaDescriptor): string {
  const lines = schema.fields.map((field) => {
    const fieldType =
      field.kind === "object"
        ? field.reference?.csharp
        : field.kind === "string"
          ? "string"
          : field.kind === "number"
            ? "float"
            : "bool";
    const fieldName = field.name;
    return `    public ${fieldType} ${fieldName};`;
  });

  return `// Auto-generated by PartyGame
using System;

namespace PartyGame.Generated
{
    [Serializable]
    public class ${schema.targets.csharp}
    {
${lines.join("\n")}
    }
}
`;
}

function renderGodot(schema: SchemaDescriptor): string {
  const lines = schema.fields.map((field) => {
    const fieldType =
      field.kind === "object"
        ? field.reference?.godot
        : field.kind === "string"
          ? "String"
          : field.kind === "number"
            ? "float"
            : "bool";
    return `\tvar ${toSnakeCase(field.name)}: ${fieldType}`;
  });

  return `class ${schema.targets.godot}:
${lines.join("\n")}
`;
}

function renderUnreal(schema: SchemaDescriptor): string {
  const lines = schema.fields.map((field) => {
    const fieldType =
      field.kind === "object"
        ? field.reference?.unreal
        : field.kind === "string"
          ? "FString"
          : field.kind === "number"
            ? "float"
            : "bool";
    const fieldName = field.kind === "object" ? field.name : field.name;
    const propertyName = fieldName.charAt(0).toUpperCase() + fieldName.slice(1);
    return `    UPROPERTY(EditAnywhere, BlueprintReadWrite) ${fieldType} ${propertyName};`;
  });

  return `// Auto-generated by PartyGame for Unreal Engine
#pragma once

#include "CoreMinimal.h"
#include "PartyGameTypes.generated.h"

USTRUCT(BlueprintType)
struct ${schema.targets.unreal}
{
    GENERATED_BODY()
${lines.join("\n")}
};
`;
}

export type GeneratedArtifacts = Record<string, string>;

export function buildGeneratedArtifacts(): GeneratedArtifacts {
  const descriptors = rootSchemas.map(({ name, schema }) =>
    describeSchema(name, schema),
  );

  const artifacts: GeneratedArtifacts = {
    "unity/package.json": JSON.stringify(
      {
        name: "com.partygame.core",
        version: "0.0.1",
        displayName: "PartyGame SDK",
        description:
          "Auto-generated PartyGame multiplayer types and client SDK.",
        unity: "2021.3",
      },
      null,
      2,
    ),
    "unity/PartyGame.asmdef": JSON.stringify(
      {
        name: "PartyGame",
        references: [],
        includePlatforms: [],
        excludePlatforms: [],
        allowUnsafeCode: false,
        overrideReferences: false,
        precompiledReferences: [],
        autoReferenced: true,
        defineConstraints: [],
        versionDefines: [],
        noEngineReferences: false,
      },
      null,
      2,
    ),
    "godot/addons/partygame/plugin.cfg": `[plugin]\n\nname="PartyGame SDK"\ndescription="Auto-generated PartyGame multiplayer types and client SDK."\nauthor="PartyGame"\nversion="0.0.1"\nscript="edge_pulse_plugin.gd"\n`,
    "godot/addons/partygame/edge_pulse_plugin.gd": `@tool\nextends EditorPlugin\n\nfunc _enter_tree():\n\tpass\n\nfunc _exit_tree():\n\tpass\n`,
    "unreal/PartyGame/PartyGame.uplugin": JSON.stringify(
      {
        FileVersion: 3,
        Version: 1,
        VersionName: "0.0.1",
        FriendlyName: "PartyGame SDK",
        Description:
          "Auto-generated PartyGame multiplayer types and client SDK.",
        Category: "Networking",
        CreatedBy: "PartyGame",
        CanContainContent: true,
        IsBetaVersion: false,
        IsExperimentalVersion: false,
        Installed: false,
        Modules: [
          { Name: "PartyGame", Type: "Runtime", LoadingPhase: "Default" },
        ],
      },
      null,
      2,
    ),
    "unreal/PartyGame/Source/PartyGame/PartyGame.Build.cs": `using UnrealBuildTool;\n\npublic class PartyGame : ModuleRules\n{\n\tpublic PartyGame(ReadOnlyTargetRules Target) : base(Target)\n\t{\n\t\tPCHUsage = ModuleRules.PCHUsageMode.UseExplicitOrSharedPCHs;\n\t\tPublicDependencyModuleNames.AddRange(new string[] { "Core", "CoreUObject", "Engine" });\n\t}\n}\n`,
    "unreal/PartyGame/Source/PartyGame/Private/PartyGameModule.cpp": `#include "Modules/ModuleManager.h"\nIMPLEMENT_MODULE(FDefaultModuleImpl, PartyGame);\n`,
  };

  artifacts["unity/Runtime/PartyGameTypes.cs"] = descriptors
    .map(renderCSharp)
    .join("\n");
  artifacts["godot/addons/partygame/edge_pulse_types.gd"] =
    `# Auto-generated by PartyGame
class_name PartyGameTypes

${descriptors.map(renderGodot).join("\n")}`;
  artifacts["unreal/PartyGame/Source/PartyGame/Public/PartyGameTypes.h"] =
    descriptors.map(renderUnreal).join("\n");

  return artifacts;
}

export function getGeneratedArtifactPaths(): string[] {
  return Object.keys(buildGeneratedArtifacts());
}
