import fs from "fs";
import path from "path";

const OUT_DIR = path.join(__dirname, "../../../clients");

// --- Unity (UPM Package) ---
function generateUnity() {
  const unityDir = path.join(OUT_DIR, "unity");
  const runtimeDir = path.join(unityDir, "Runtime");
  fs.mkdirSync(runtimeDir, { recursive: true });

  fs.writeFileSync(path.join(unityDir, "package.json"), JSON.stringify({
    name: "com.partygame.core",
    version: "0.0.1",
    displayName: "PartyGame SDK",
    description: "Auto-generated PartyGame multiplayer types and client SDK.",
    unity: "2021.3"
  }, null, 2));

  fs.writeFileSync(path.join(unityDir, "PartyGame.asmdef"), JSON.stringify({
    name: "PartyGame",
    references: [],
    includePlatforms: [],
    excludePlatforms: [],
    allowUnsafeCode: false,
    overrideReferences: false,
    precompiledReferences: [],
    autoReferenced: true,
    defineConstraints: [],
    versionDefines: [],
    noEngineReferences: false
  }, null, 2));

  fs.writeFileSync(path.join(runtimeDir, "PartyGameTypes.cs"), `// Auto-generated by PartyGame
using System;

namespace PartyGame.Generated
{
    [Serializable]
    public class Vector3 { public float x; public float y; public float z; }

    [Serializable]
    public class PlayerState { public string id; public Vector3 position; public Vector3 rotation; public float health; }

    [Serializable]
    public class PurchaseRequest { public string itemId; public float cost; public string idempotencyKey; }
}
`);
}

// --- Godot (Standard Addon) ---
function generateGodot() {
  const godotDir = path.join(OUT_DIR, "godot/addons/partygame");
  fs.mkdirSync(godotDir, { recursive: true });

  fs.writeFileSync(path.join(godotDir, "plugin.cfg"), `[plugin]

name="PartyGame SDK"
description="Auto-generated PartyGame multiplayer types and client SDK."
author="PartyGame"
version="0.0.1"
script="edge_pulse_plugin.gd"
`);

  fs.writeFileSync(path.join(godotDir, "edge_pulse_plugin.gd"), `@tool
extends EditorPlugin

function _enter_tree():
\tpass

function _exit_tree():
\tpass
`);

  fs.writeFileSync(path.join(godotDir, "edge_pulse_types.gd"), `# Auto-generated by PartyGame
class_name PartyGameTypes

class Vector3State:
\tvar x: float
\tvar y: float
\tvar z: float

class PlayerState:
\tvar id: String
\tvar position: Vector3State
\tvar rotation: Vector3State
\tvar health: float

class PurchaseRequest:
\tvar item_id: String
\tvar cost: float
\tvar idempotency_key: String
`);
}

// --- Unreal Engine (Standard Plugin) ---
function generateUnreal() {
  const unrealDir = path.join(OUT_DIR, "unreal/PartyGame");
  const sourceDir = path.join(unrealDir, "Source/PartyGame");
  const publicDir = path.join(sourceDir, "Public");
  const privateDir = path.join(sourceDir, "Private");

  fs.mkdirSync(publicDir, { recursive: true });
  fs.mkdirSync(privateDir, { recursive: true });

  fs.writeFileSync(path.join(unrealDir, "PartyGame.uplugin"), JSON.stringify({
    FileVersion: 3,
    Version: 1,
    VersionName: "0.0.1",
    FriendlyName: "PartyGame SDK",
    Description: "Auto-generated PartyGame multiplayer types and client SDK.",
    Category: "Networking",
    CreatedBy: "PartyGame",
    CanContainContent: true,
    IsBetaVersion: false,
    IsExperimentalVersion: false,
    Installed: false,
    Modules: [
      {
        Name: "PartyGame",
        Type: "Runtime",
        LoadingPhase: "Default"
      }
    ]
  }, null, 2));

  fs.writeFileSync(path.join(sourceDir, "PartyGame.Build.cs"), `using UnrealBuildTool;

public class PartyGame : ModuleRules
{
\tpublic PartyGame(ReadOnlyTargetRules Target) : base(Target)
\t{
\t\tPCHUsage = ModuleRules.PCHUsageMode.UseExplicitOrSharedPCHs;
\t\tPublicDependencyModuleNames.AddRange(new string[] { "Core", "CoreUObject", "Engine" });
\t}
}
`);

  fs.writeFileSync(path.join(privateDir, "PartyGameModule.cpp"), `#include "Modules/ModuleManager.h"
IMPLEMENT_MODULE(FDefaultModuleImpl, PartyGame);
`);

  fs.writeFileSync(path.join(publicDir, "PartyGameTypes.h"), `// Auto-generated by PartyGame for Unreal Engine
#pragma once

#include "CoreMinimal.h"
#include "PartyGameTypes.generated.h"

USTRUCT(BlueprintType)
struct FPartyGameVector3
{
    GENERATED_BODY()
    UPROPERTY(EditAnywhere, BlueprintReadWrite) float X = 0.0f;
    UPROPERTY(EditAnywhere, BlueprintReadWrite) float Y = 0.0f;
    UPROPERTY(EditAnywhere, BlueprintReadWrite) float Z = 0.0f;
};

USTRUCT(BlueprintType)
struct FPartyGamePlayerState
{
    GENERATED_BODY()
    UPROPERTY(EditAnywhere, BlueprintReadWrite) FString Id;
    UPROPERTY(EditAnywhere, BlueprintReadWrite) FPartyGameVector3 Position;
    UPROPERTY(EditAnywhere, BlueprintReadWrite) FPartyGameVector3 Rotation;
    UPROPERTY(EditAnywhere, BlueprintReadWrite) float Health = 0.0f;
};

USTRUCT(BlueprintType)
struct FPartyGamePurchaseRequest
{
    GENERATED_BODY()
    UPROPERTY(EditAnywhere, BlueprintReadWrite) FString ItemId;
    UPROPERTY(EditAnywhere, BlueprintReadWrite) float Cost = 0.0f;
    UPROPERTY(EditAnywhere, BlueprintReadWrite) FString IdempotencyKey;
};
`);
}

function main() {
  generateUnity();
  generateGodot();
  generateUnreal();
  console.log("Successfully generated standard Plugins for Unity (UPM), Godot (Addon), and Unreal (uplugin)!");
}

main();
