// Auto-generated by PartyGame
using System;

namespace PartyGame.Generated
{
    [Serializable]
    public class TransformComponent
    {
    public float x;
    public float y;
    public float rotation;
    public float scaleX;
    public float scaleY;
    }
}

// Auto-generated by PartyGame
using System;

namespace PartyGame.Generated
{
    [Serializable]
    public class HealthComponent
    {
    public float hp;
    public float maxHp;
    public bool isDead;
    }
}

// Auto-generated by PartyGame
using System;

namespace PartyGame.Generated
{
    [Serializable]
    public class VelocityComponent
    {
    public float vx;
    public float vy;
    }
}

// Auto-generated by PartyGame
using System;

namespace PartyGame.Generated
{
    [Serializable]
    public class InputComponent
    {
    public float moveX;
    public float moveY;
    public bool isJumping;
    public bool isSprinting;
    }
}
